apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: testgo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testgo 
  name: testgo
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: testgo 
